version: '3.7'

services:
  postgres:
    container_name: fs-apollo-db
    image: postgres:12
    restart: always
    ports:
      - '55432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - fs-apollo-db:/var/lib/postgresql/data
volumes:
  fs-apollo-db:
