version: "3.6"

services:
  postgres:
    image: postgres:11.10
    ports:
      - "55432:5432"
    environment:
      - "POSTGRES_DB: ${POSTGRES_DB}"
      - "POSTGRES_USER: ${POSTGRES_USER}"
      - "POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}"
